# Generated by Django 2.2.6 on 2019-11-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20191104_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
