# Generated by Django 2.2.6 on 2019-11-06 13:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_nmber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
