# Generated by Django 2.2.6 on 2019-11-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_user_phone_nmber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
