# Generated by Django 2.2.6 on 2019-11-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_nmber',
            new_name='phone',
        ),
    ]
