# Generated by Django 2.2.6 on 2019-11-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20191106_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
