# Generated by Django 2.2.7 on 2019-11-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191108_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('going well', 'Everything going well'), ('behind', 'Behind Deadline'), ('crisis', 'Crisis'), ('finish', 'finished'), ('fail', 'Fail')], default='Everything going well', max_length=200),
        ),
    ]
