# Generated by Django 2.2.7 on 2019-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20191118_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskallocation',
            name='allocation',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
