# Generated by Django 2.2.7 on 2019-11-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191118_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('underqa', 'Under QA'), ('underuat', 'Under UAT'), ('approved', 'Approved'), ('merged', 'Merged')], default='Created', max_length=200),
        ),
    ]
