# Generated by Django 2.2.7 on 2019-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20191119_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weightage',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
