# Generated by Django 2.2.7 on 2019-11-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='weightage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
