# Generated by Django 2.2.7 on 2019-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20191119_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskallocation',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('UI Designer', 'UI Designer'), ('QA', 'QA')], max_length=201),
        ),
    ]
