# Generated by Django 2.2.6 on 2019-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('fail', 'Fail'), ('crisis', 'Crisis'), ('behind', 'Behind Deadline'), ('going well', 'Everything going well')], default=1, max_length=1)),
            ],
        ),
    ]
