# Generated by Django 2.2.6 on 2019-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('fail', 'Fail'), ('crisis', 'Crisis'), ('behind', 'Behind Deadline'), ('going well', 'Everything going well')], default=4, max_length=200),
        ),
    ]
