# Generated by Django 2.2.6 on 2019-11-07 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20191107_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('fail', 'Fail'), ('crisis', 'Crisis'), ('behind', 'Behind Deadline'), ('going well', 'Everything going well'), ('finish', 'finished')], default=4, max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('1', 'Developer'), ('2', 'UI Designer'), ('3', 'QA')], max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
