# Generated by Django 2.2.6 on 2019-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191107_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='role',
            field=models.CharField(choices=[('1', 'Developer'), ('2', 'UI Designer'), ('3', 'QA')], default='Team Leader', max_length=201),
        ),
    ]
