# Generated by Django 2.2.6 on 2019-11-07 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20191107_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='role',
            field=models.CharField(choices=[('1', 'Developer'), ('2', 'UI Designer'), ('3', 'QA')], max_length=201),
        ),
        migrations.CreateModel(
            name='Teamlead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
