# Generated by Django 2.2.6 on 2019-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191112_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='allocation',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
