# Generated by Django 2.2.7 on 2019-11-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191119_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('underprogress', 'Under progress'), ('created', 'Created'), ('closed', 'Closed')], default='created', max_length=200),
        ),
    ]
