# Generated by Django 2.2.7 on 2019-11-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20191119_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('ui designer', 'UI Designer'), ('QA', 'QA')], max_length=201),
        ),
    ]
