# Generated by Django 2.2.7 on 2019-11-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20191119_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='role',
            field=models.CharField(choices=[('1', 'Developer'), ('2', 'UI Designer'), ('3', 'QA')], max_length=201),
        ),
    ]
