# Generated by Django 2.2.7 on 2019-11-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20191119_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('UI Designer', 'UI Designer'), ('QA', 'QA')], max_length=201),
        ),
    ]
